### PR TITLE
Added Doubly Linked List Implementation

### PR DESCRIPTION
**Pull request by KSHITIZ-RAJ-22**

### CODE REVIEW

**Comment by laasyagupta2005** [comment]
Kindly use proper spaces between operators and variables.

**Comment by laasyagupta2005** [comment]
Use this link to format your C++ code.

https://codebeautify.org/cpp-formatter-beautifier

**Comment by KSHITIZ-RAJ-22** [comment]
Formatted the document by giving proper spacing between variables and operators.

**Comment by laasyagupta2005** [comment]
Accepted

**Pull request merged**
